# Generated by Django 4.1.4 on 2022-12-29 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0002_remove_menuitem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='rank',
        ),
    ]
