# Generated by Django 4.1.4 on 2022-12-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_app', '0004_menuitem_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='rank',
        ),
    ]
